language: python
sudo: false

python:
  - '3.8'
env:
  - TOXENV=quality
  - TOXENV=django31
  - TOXENV=django32
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.25.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export BOKCHOY_HEADLESS=true

addons:
  firefox: latest

services:
  - xvfb

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success: coveralls
